const candidates = [
    {
        id: 1,
        name: 'Abhivyakti Sharma',
        jobTitle: 'software-engineer',
        appliedFor: 'Lead Web Developer',
        experience: '0-1',
        matchPercentage: '100%',
        skills: [
            { id: 'skill-javascript', name: 'JavaScript', rating: 4 },
            { id: 'skill-react', name: 'React', rating: 3 },
            { id: 'skill-angular', name: 'Angular JS', rating: 5 },
        ],
        email: '********@gmail.com',
        phone: '******6655',
        location: 'location-new-york',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-aws',
        isTopProfile: false
    },
    {
        id: 2,
        name: 'Rahul Patel',
        jobTitle: 'product-manager',
        appliedFor: 'Senior Product Manager',
        experience: '4-5',
        matchPercentage: '85%',
        skills: [
            { id: 'skill-javascript', name: 'JavaScript', rating: 5 },
            { id: 'skill-react', name: 'React', rating: 4 },
            { id: 'skill-html', name: 'HTML', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******1234',
        location: 'location-san-francisco',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-remote',
        certification: 'certification-google-cloud',
        isTopProfile: true
    },
    {
        id: 3,
        name: 'Neha Gupta',
        jobTitle: 'data-scientist',
        appliedFor: 'Senior Backend Developer',
        experience: '2-3',
        matchPercentage: '92%',
        skills: [
            { id: 'skill-nodejs', name: 'Node.js', rating: 4 },
            { id: 'skill-express', name: 'Express.js', rating: 3 },
            { id: 'skill-mongodb', name: 'MongoDB', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******5678',
        location: 'location-austin',
        jobType: 'job-type-contract',
        jobPreference: 'job-preference-hybrid',
        certification: 'certification-scrum',
        isTopProfile: false
    },
    {
        id: 4,
        name: 'Amit Kumar',
        jobTitle: 'software-engineer',
        appliedFor: 'Full Stack Developer',
        experience: '6+',
        matchPercentage: '88%',
        skills: [
            { id: 'skill-javascript', name: 'JavaScript', rating: 4 },
            { id: 'skill-react', name: 'React', rating: 5 },
            { id: 'skill-nodejs', name: 'Node.js', rating: 5 },
        ],
        email: '********@example.com',
        phone: '******9101',
        location: 'location-remote',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-remote',
        certification: 'certification-aws',
        isTopProfile: true
    },
    {
        id: 5,
        name: 'Priya Singh',
        jobTitle: 'product-manager',
        appliedFor: 'Senior UI/UX Designer',
        experience: '0-1',
        matchPercentage: '90%',
        skills: [
            { id: 'skill-sketch', name: 'Sketch', rating: 5 },
            { id: 'skill-figma', name: 'Figma', rating: 4 },
            { id: 'skill-adobexd', name: 'Adobe XD', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******1122',
        location: 'location-new-york',
        jobType: 'job-type-part-time',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-google-cloud',
        isTopProfile: false
    },
    {
        id: 6,
        name: 'Sunita Mehta',
        jobTitle: 'data-scientist',
        appliedFor: 'Data Analyst',
        experience: '2-3',
        matchPercentage: '91%',
        skills: [
            { id: 'skill-python', name: 'Python', rating: 5 },
            { id: 'skill-r', name: 'R', rating: 4 },
            { id: 'skill-sql', name: 'SQL', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******3344',
        location: 'location-austin',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-hybrid',
        certification: 'certification-google-cloud',
        isTopProfile: false
    },
    {
        id: 7,
        name: 'Rajesh Khanna',
        jobTitle: 'software-engineer',
        appliedFor: 'Backend Developer',
        experience: '4-5',
        matchPercentage: '87%',
        skills: [
            { id: 'skill-java', name: 'Java', rating: 5 },
            { id: 'skill-spring', name: 'Spring', rating: 4 },
            { id: 'skill-hibernate', name: 'Hibernate', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******5566',
        location: 'location-san-francisco',
        jobType: 'job-type-contract',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-scrum',
        isTopProfile: false
    },
    {
        id: 8,
        name: 'Anita Desai',
        jobTitle: 'product-manager',
        appliedFor: 'Product Owner',
        experience: '6+',
        matchPercentage: '95%',
        skills: [
            { id: 'skill-agile', name: 'Agile', rating: 5 },
            { id: 'skill-scrum', name: 'Scrum', rating: 4 },
            { id: 'skill-jira', name: 'JIRA', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******7788',
        location: 'location-new-york',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-remote',
        certification: 'certification-aws',
        isTopProfile: false
    },
    {
        id: 9,
        name: 'Vikas Reddy',
        jobTitle: 'data-scientist',
        appliedFor: 'Data Scientist',
        experience: '2-3',
        matchPercentage: '89%',
        skills: [
            { id: 'skill-python', name: 'Python', rating: 4 },
            { id: 'skill-tensorflow', name: 'TensorFlow', rating: 4 },
            { id: 'skill-pytorch', name: 'PyTorch', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******9900',
        location: 'location-remote',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-google-cloud',
        isTopProfile: false
    },
    {
        id: 10,
        name: 'Meena Kaur',
        jobTitle: 'software-engineer',
        appliedFor: 'Frontend Developer',
        experience: '0-1',
        matchPercentage: '84%',
        skills: [
            { id: 'skill-html', name: 'HTML', rating: 4 },
            { id: 'skill-css', name: 'CSS', rating: 4 },
            { id: 'skill-javascript', name: 'JavaScript', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******1123',
        location: 'location-austin',
        jobType: 'job-type-part-time',
        jobPreference: 'job-preference-hybrid',
        certification: 'certification-aws',
        isTopProfile: false
    },
    {
        id: 11,
        name: 'Suresh Gupta',
        jobTitle: 'product-manager',
        appliedFor: 'Project Manager',
        experience: '6+',
        matchPercentage: '93%',
        skills: [
            { id: 'skill-management', name: 'Management', rating: 5 },
            { id: 'skill-planning', name: 'Planning', rating: 4 },
            { id: 'skill-scheduling', name: 'Scheduling', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******4455',
        location: 'location-san-francisco',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-scrum',
        isTopProfile: false
    },
    {
        id: 12,
        name: 'Anjali Verma',
        jobTitle: 'data-scientist',
        appliedFor: 'Machine Learning Engineer',
        experience: '4-5',
        matchPercentage: '96%',
        skills: [
            { id: 'skill-python', name: 'Python', rating: 5 },
            { id: 'skill-machine-learning', name: 'Machine Learning', rating: 5 },
            { id: 'skill-data-science', name: 'Data Science', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******6677',
        location: 'location-remote',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-remote',
        certification: 'certification-google-cloud',
        isTopProfile: true
    },
    {
        id: 13,
        name: 'Rohit Sharma',
        jobTitle: 'software-engineer',
        appliedFor: 'DevOps Engineer',
        experience: '2-3',
        matchPercentage: '85%',
        skills: [
            { id: 'skill-jenkins', name: 'Jenkins', rating: 4 },
            { id: 'skill-docker', name: 'Docker', rating: 4 },
            { id: 'skill-kubernetes', name: 'Kubernetes', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******7789',
        location: 'location-austin',
        jobType: 'job-type-contract',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-aws',
        isTopProfile: false
    },
    {
        id: 14,
        name: 'Kavita Joshi',
        jobTitle: 'product-manager',
        appliedFor: 'Business Analyst',
        experience: '4-5',
        matchPercentage: '92%',
        skills: [
            { id: 'skill-analysis', name: 'Analysis', rating: 5 },
            { id: 'skill-requirements', name: 'Requirements Gathering', rating: 4 },
            { id: 'skill-communication', name: 'Communication', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******9901',
        location: 'location-san-francisco',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-remote',
        certification: 'certification-scrum',
        isTopProfile: false
    },
    {
        id: 15,
        name: 'Deepak Sharma',
        jobTitle: 'data-scientist',
        appliedFor: 'Data Engineer',
        experience: '0-1',
        matchPercentage: '89%',
        skills: [
            { id: 'skill-python', name: 'Python', rating: 4 },
            { id: 'skill-spark', name: 'Apache Spark', rating: 4 },
            { id: 'skill-hadoop', name: 'Hadoop', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******4456',
        location: 'location-new-york',
        jobType: 'job-type-part-time',
        jobPreference: 'job-preference-hybrid',
        certification: 'certification-google-cloud',
        isTopProfile: false
    },
    {
        id: 16,
        name: 'Pooja Mehta',
        jobTitle: 'software-engineer',
        appliedFor: 'Software Engineer',
        experience: '2-3',
        matchPercentage: '88%',
        skills: [
            { id: 'skill-csharp', name: 'C#', rating: 4 },
            { id: 'skill-dotnet', name: '.NET', rating: 4 },
            { id: 'skill-azure', name: 'Azure', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******6678',
        location: 'location-austin',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-aws',
        isTopProfile: false
    },
    {
        id: 17,
        name: 'Arjun Singh',
        jobTitle: 'product-manager',
        appliedFor: 'Technical Product Manager',
        experience: '6+',
        matchPercentage: '90%',
        skills: [
            { id: 'skill-product-management', name: 'Product Management', rating: 5 },
            { id: 'skill-roadmapping', name: 'Roadmapping', rating: 4 },
            { id: 'skill-agile', name: 'Agile', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******7780',
        location: 'location-remote',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-remote',
        certification: 'certification-scrum',
        isTopProfile: false
    },
    {
        id: 18,
        name: 'Nisha Gupta',
        jobTitle: 'data-scientist',
        appliedFor: 'AI Engineer',
        experience: '4-5',
        matchPercentage: '95%',
        skills: [
            { id: 'skill-python', name: 'Python', rating: 5 },
            { id: 'skill-deep-learning', name: 'Deep Learning', rating: 5 },
            { id: 'skill-neural-networks', name: 'Neural Networks', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******8890',
        location: 'location-new-york',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-hybrid',
        certification: 'certification-google-cloud',
        isTopProfile: false
    },
    {
        id: 19,
        name: 'Vikram Thakur',
        jobTitle: 'software-engineer',
        appliedFor: 'Frontend Engineer',
        experience: '2-3',
        matchPercentage: '87%',
        skills: [
            { id: 'skill-react', name: 'React', rating: 5 },
            { id: 'skill-javascript', name: 'JavaScript', rating: 4 },
            { id: 'skill-css', name: 'CSS', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******1123',
        location: 'location-san-francisco',
        jobType: 'job-type-contract',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-aws',
        isTopProfile: false
    },
    {
        id: 20,
        name: 'Ankur Yadav',
        jobTitle: 'product-manager',
        appliedFor: 'Senior Product Manager',
        experience: '6+',
        matchPercentage: '94%',
        skills: [
            { id: 'skill-product-management', name: 'Product Management', rating: 5 },
            { id: 'skill-strategy', name: 'Strategy', rating: 4 },
            { id: 'skill-leadership', name: 'Leadership', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******3345',
        location: 'location-new-york',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-aws',
        isTopProfile: false
    },
    {
        id: 21,
        name: 'Sneha Kapoor',
        jobTitle: 'data-scientist',
        appliedFor: 'Data Analyst',
        experience: '0-1',
        matchPercentage: '90%',
        skills: [
            { id: 'skill-python', name: 'Python', rating: 5 },
            { id: 'skill-sql', name: 'SQL', rating: 4 },
            { id: 'skill-excel', name: 'Excel', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******1122',
        location: 'location-new-york',
        jobType: 'job-type-part-time',
        jobPreference: 'job-preference-hybrid',
        certification: 'certification-google-cloud',
        isTopProfile: false
    },
    {
        id: 22,
        name: 'Karan Mehta',
        jobTitle: 'software-engineer',
        appliedFor: 'Backend Developer',
        experience: '2-3',
        matchPercentage: '88%',
        skills: [
            { id: 'skill-java', name: 'Java', rating: 4 },
            { id: 'skill-spring', name: 'Spring', rating: 4 },
            { id: 'skill-mysql', name: 'MySQL', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******3344',
        location: 'location-san-francisco',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-aws',
        isTopProfile: false
    },
    {
        id: 23,
        name: 'Sanya Verma',
        jobTitle: 'product-manager',
        appliedFor: 'Project Manager',
        experience: '4-5',
        matchPercentage: '89%',
        skills: [
            { id: 'skill-management', name: 'Management', rating: 5 },
            { id: 'skill-planning', name: 'Planning', rating: 4 },
            { id: 'skill-budgeting', name: 'Budgeting', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******5566',
        location: 'location-austin',
        jobType: 'job-type-contract',
        jobPreference: 'job-preference-onsite',
        certification: 'certification-scrum',
        isTopProfile: false
    },
    {
        id: 24,
        name: 'Ravi Patel',
        jobTitle: 'data-scientist',
        appliedFor: 'AI Engineer',
        experience: '6+',
        matchPercentage: '93%',
        skills: [
            { id: 'skill-python', name: 'Python', rating: 5 },
            { id: 'skill-tensorflow', name: 'TensorFlow', rating: 4 },
            { id: 'skill-neural-networks', name: 'Neural Networks', rating: 4 },
        ],
        email: '********@example.com',
        phone: '******7788',
        location: 'location-new-york',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-remote',
        certification: 'certification-google-cloud',
        isTopProfile: false
    },
    {
        id: 25,
        name: 'Aishwarya Rai',
        jobTitle: 'software-engineer',
        appliedFor: 'Software Engineer',
        experience: '0-1',
        matchPercentage: '87%',
        skills: [
            { id: 'skill-javascript', name: 'JavaScript', rating: 4 },
            { id: 'skill-react', name: 'React', rating: 4 },
            { id: 'skill-nodejs', name: 'Node.js', rating: 3 },
        ],
        email: '********@example.com',
        phone: '******8890',
        location: 'location-austin',
        jobType: 'job-type-full-time',
        jobPreference: 'job-preference-hybrid',
        certification: 'certification-aws',
        isTopProfile: false
    },
];

export default candidates;
